### ISSUE TITLE
可否增加一个使用的示例

### ISSUE THREAD

**Issue by kuangshenyan** [zhfjyq/vscode-plugin-drawio#1]
可否增加一个使用示例，刚才试用了下，但是没太用明白。

**Comment by mmrelease** [comment]
[ 创建流程图 ]
0. 打开 markdown 文件
1. 移动光标到希望插入流程图的行
2. 点击工具栏小图标进入 Drawio
3. 选择文件存储地址: Browser [重要！！，必须选择才能做到同步]
4. 选择新建流程图
5. 在弹出对话框中修改流程图扩展名为svg，文件名自定.
6. 任何时候，点击保存或者【ctrl+S】,文件将自动同步到和.md文件同级目录下的drawio_assets子目录下.
[ 打开已有流程图 ]
0. 打开markdown 文件
1. 当前同级目录下的drawio_assets中内容将被同步到浏览器
2. 随后编辑同上

**Comment by zhfjyq** [comment]
更新了说明文件，请参考
