### ISSUE TITLE
支持一下中文界面

### ISSUE THREAD

**Issue by darcyg** [zhfjyq/vscode-plugin-drawio#2]
hi zhfjyq:
    在vscode中打开drawio之后，发现如下问题
![0001](https://user-images.githubusercontent.com/3241763/70848698-58bbc700-1eb0-11ea-854a-175321cbee0e.png)
界面不支持中文，另外也没有模板选择框
    我用的系统是ubuntu 16.04 LTS x64

**Comment by darcyg** [comment]
能否支持配置本地(本机)或局域网服务器
默认参数不要加offline=1(就有模板库)

**Comment by zhfjyq** [comment]
1.手动去掉offline=1就可以选择中文和模板库
2. 如果你想默认不需要 offline，直接修改vscode 设置 “drawio.offline” 从 true 改为 false
![image](https://user-images.githubusercontent.com/2638113/71051528-95731100-2183-11ea-8f7a-95c62f819fd3.png)
