### ISSUE TITLE
svg文件未能下载到指定目录

### ISSUE THREAD

**Issue by linkypi** [zhfjyq/vscode-plugin-drawio#3]
保存svg文件后，文件并没有下载到 drawio_assets 文件夹，而是下载到了计算机的Download目录
![image](https://user-images.githubusercontent.com/4386639/72029189-14112900-32c0-11ea-863a-0decd7a411ef.png)

**Comment by zhfjyq** [comment]
你必须选择存储位置为浏览器，才能够自动保存到 vscode 中
![image](https://user-images.githubusercontent.com/2638113/72310330-73a27680-36bc-11ea-94d7-024eeb7a8668.png)
